import type { Locale } from "./types";

export const ENGLISH_MESSAGES = {
  news: "News", map: "Map", all: "All countries", latest: "Latest news", sources: "Sources", related: "Related events", readMore: "Read story", back: "Back to news", language: "Language", region: "Region", automatic: "Automatic", published: "Published", updated: "Updated", empty: "No published stories for this region yet.", unavailable: "No related live markets are available right now.", live: "Live odds", track: "Track in DropsBot", market: "View market", yes: "YES", no: "NO", volume: "Volume", translated: "Machine translated · English original", original: "View original", about: "About this newsdesk", description: "World events. Clear context. Live probabilities.", archive: "Archive", loadMore: "Load more", zoomIn: "Zoom in", zoomOut: "Zoom out", close: "Close", change: "Odds change · 7D", previousMarket: "Previous market at this location", nextMarket: "Next market at this location", marketNumber: "Market", of: "of", loadingMap: "Loading live map…", mapUnavailable: "Interactive map unavailable", mapStartFailed: "The interactive map could not start.", fallbackSummary: "The latest verified event list remains available as a text summary.", marketControls: "Map controls", selectEvent: "Select event", marketActivity: "Live market activity", dismiss: "Dismiss activity notification", refreshing: "Updating odds…", search: "Search news", noResults: "No stories match this search.", feed: "RSS feed", country: "Country", browseMap: "Explore the map", sourceDate: "Source date", countryNews: "Country news", settings: "Language and region", editorial: "Independent context, linked to the original reporting.", viewSource: "Read source", minute: "min read",
} as const;
export type MessageKey = keyof typeof ENGLISH_MESSAGES;
const ORDER: MessageKey[] = ["news", "map", "all", "latest", "sources", "related", "readMore", "back", "language", "region", "automatic", "published", "updated", "empty", "unavailable", "live", "track", "market", "yes", "no", "volume", "translated", "original", "about", "description", "archive", "loadMore", "zoomIn", "zoomOut", "close", "change", "previousMarket", "nextMarket", "marketNumber", "of", "loadingMap", "mapUnavailable", "mapStartFailed", "fallbackSummary", "marketControls", "selectEvent", "marketActivity", "dismiss", "refreshing", "search", "noResults", "feed", "country", "browseMap", "sourceDate", "countryNews", "settings", "editorial", "viewSource", "minute"];
const translations: Record<Exclude<Locale,"en">, string[]> = {
  ru: ["Новости","Карта","Все страны","Последние новости","Источники","Связанные события","Читать","К новостям","Язык","Регион","Автоматически","Опубликовано","Обновлено","В этом регионе пока нет опубликованных новостей.","Подходящих активных рынков сейчас нет.","Текущие вероятности","Отслеживать в DropsBot","Открыть рынок","ДА","НЕТ","Объём","Машинный перевод · Оригинал на английском","Открыть оригинал","О редакции","Мировые события. Понятный контекст. Текущие вероятности.","Архив","Загрузить ещё","Приблизить","Отдалить","Закрыть","Изменение вероятности · 7 дн.","Предыдущий рынок в этой точке","Следующий рынок в этой точке","Рынок","из","Загружаем карту…","Интерактивная карта недоступна","Не удалось запустить карту.","Последние проверенные события доступны в списке.","Управление картой","Выбрать событие","Активность рынков","Скрыть уведомление","Обновляем вероятности…","Поиск новостей","По вашему запросу ничего не найдено.","RSS-лента","Страна","Открыть карту","Дата источника","Новости страны","Язык и регион","Независимый контекст со ссылками на первоисточники.","Читать источник","мин. чтения"],
  uk: ["Новини","Карта","Усі країни","Останні новини","Джерела","Пов’язані події","Читати","До новин","Мова","Регіон","Автоматично","Опубліковано","Оновлено","У цьому регіоні ще немає опублікованих новин.","Відповідних активних ринків зараз немає.","Поточні ймовірності","Стежити в DropsBot","Відкрити ринок","ТАК","НІ","Обсяг","Машинний переклад · Оригінал англійською","Переглянути оригінал","Про редакцію","Світові події. Зрозумілий контекст. Поточні ймовірності.","Архів","Завантажити ще","Наблизити","Віддалити","Закрити","Зміна ймовірності · 7 дн.","Попередній ринок у цій точці","Наступний ринок у цій точці","Ринок","із","Завантажуємо карту…","Інтерактивна карта недоступна","Не вдалося запустити карту.","Останні перевірені події доступні у списку.","Керування картою","Вибрати подію","Активність ринків","Приховати сповіщення","Оновлюємо ймовірності…","Пошук новин","За вашим запитом нічого не знайдено.","RSS-стрічка","Країна","Відкрити карту","Дата джерела","Новини країни","Мова й регіон","Незалежний контекст із посиланнями на першоджерела.","Читати джерело","хв читання"],
  de: ["Nachrichten","Karte","Alle Länder","Aktuelle Nachrichten","Quellen","Verwandte Ereignisse","Artikel lesen","Zurück zu Nachrichten","Sprache","Region","Automatisch","Veröffentlicht","Aktualisiert","Noch keine Nachrichten für diese Region.","Derzeit sind keine passenden aktiven Märkte verfügbar.","Live-Wahrscheinlichkeiten","In DropsBot verfolgen","Markt öffnen","JA","NEIN","Volumen","Maschinell übersetzt · Englisches Original","Original anzeigen","Über die Redaktion","Weltgeschehen. Klarer Kontext. Aktuelle Wahrscheinlichkeiten.","Archiv","Mehr laden","Vergrößern","Verkleinern","Schließen","Änderung · 7 Tage","Vorheriger Markt an diesem Ort","Nächster Markt an diesem Ort","Markt","von","Karte wird geladen…","Interaktive Karte nicht verfügbar","Die Karte konnte nicht gestartet werden.","Die zuletzt geprüften Ereignisse sind als Liste verfügbar.","Kartensteuerung","Ereignis auswählen","Marktaktivität","Benachrichtigung ausblenden","Wahrscheinlichkeiten werden aktualisiert…","Nachrichten suchen","Keine passenden Artikel gefunden.","RSS-Feed","Land","Karte erkunden","Quelldatum","Ländernachrichten","Sprache und Region","Unabhängiger Kontext mit Links zu den Originalberichten.","Quelle lesen","Min. Lesezeit"],
  es: ["Noticias","Mapa","Todos los países","Últimas noticias","Fuentes","Eventos relacionados","Leer artículo","Volver a noticias","Idioma","Región","Automático","Publicado","Actualizado","Todavía no hay noticias de esta región.","No hay mercados activos relacionados en este momento.","Probabilidades en vivo","Seguir en DropsBot","Ver mercado","SÍ","NO","Volumen","Traducción automática · Original en inglés","Ver original","Sobre la redacción","Eventos mundiales. Contexto claro. Probabilidades en vivo.","Archivo","Cargar más","Acercar","Alejar","Cerrar","Cambio de probabilidad · 7 días","Mercado anterior en este lugar","Siguiente mercado en este lugar","Mercado","de","Cargando el mapa…","Mapa interactivo no disponible","No se pudo iniciar el mapa.","Los últimos eventos verificados están disponibles en la lista.","Controles del mapa","Elegir evento","Actividad del mercado","Ocultar notificación","Actualizando probabilidades…","Buscar noticias","No hay artículos que coincidan.","Canal RSS","País","Explorar el mapa","Fecha de la fuente","Noticias por país","Idioma y región","Contexto independiente con enlaces a los reportajes originales.","Leer fuente","min de lectura"],
  "pt-BR": ["Notícias","Mapa","Todos os países","Últimas notícias","Fontes","Eventos relacionados","Ler matéria","Voltar às notícias","Idioma","Região","Automático","Publicado","Atualizado","Ainda não há notícias desta região.","Não há mercados ativos relacionados no momento.","Probabilidades ao vivo","Acompanhar no DropsBot","Ver mercado","SIM","NÃO","Volume","Tradução automática · Original em inglês","Ver original","Sobre a redação","Acontecimentos mundiais. Contexto claro. Probabilidades ao vivo.","Arquivo","Carregar mais","Ampliar","Reduzir","Fechar","Variação de probabilidade · 7 dias","Mercado anterior neste local","Próximo mercado neste local","Mercado","de","Carregando o mapa…","Mapa interativo indisponível","Não foi possível iniciar o mapa.","Os últimos eventos verificados estão disponíveis na lista.","Controles do mapa","Selecionar evento","Atividade do mercado","Ocultar notificação","Atualizando probabilidades…","Buscar notícias","Nenhuma matéria encontrada.","Feed RSS","País","Explorar o mapa","Data da fonte","Notícias por país","Idioma e região","Contexto independente com links para as reportagens originais.","Ler fonte","min de leitura"],
  fr: ["Actualités","Carte","Tous les pays","Dernières actualités","Sources","Événements associés","Lire l’article","Retour aux actualités","Langue","Région","Automatique","Publié","Mis à jour","Aucun article pour cette région pour le moment.","Aucun marché actif associé n’est disponible actuellement.","Probabilités en direct","Suivre dans DropsBot","Voir le marché","OUI","NON","Volume","Traduction automatique · Original en anglais","Voir l’original","À propos de la rédaction","Événements mondiaux. Contexte clair. Probabilités en direct.","Archives","Charger plus","Agrandir","Réduire","Fermer","Évolution des probabilités · 7 j","Marché précédent à cet endroit","Marché suivant à cet endroit","Marché","sur","Chargement de la carte…","Carte interactive indisponible","La carte n’a pas pu démarrer.","Les derniers événements vérifiés sont disponibles dans la liste.","Commandes de la carte","Choisir un événement","Activité des marchés","Masquer la notification","Mise à jour des probabilités…","Rechercher des articles","Aucun article correspondant.","Flux RSS","Pays","Explorer la carte","Date de la source","Actualités par pays","Langue et région","Un contexte indépendant lié aux reportages originaux.","Lire la source","min de lecture"],
  zh: ["新闻","地图","所有国家","最新新闻","来源","相关事件","阅读报道","返回新闻","语言","地区","自动","发布时间","更新时间","该地区暂无已发布的新闻。","目前没有相关的活跃市场。","实时概率","在 DropsBot 中追踪","查看市场","是","否","交易量","机器翻译 · 英文原文","查看原文","关于编辑部","全球事件。清晰背景。实时概率。","归档","加载更多","放大","缩小","关闭","概率变化 · 7天","此位置的上一个市场","此位置的下一个市场","市场","共","正在加载地图…","交互地图不可用","地图无法启动。","最新核实的事件仍可在列表中查看。","地图控制","选择事件","市场动态","关闭通知","正在更新概率…","搜索新闻","未找到匹配的报道。","RSS 订阅","国家","探索地图","来源日期","各国新闻","语言与地区","独立背景分析，附原始报道链接。","阅读来源","分钟阅读"],
  ko: ["뉴스","지도","모든 국가","최신 뉴스","출처","관련 이벤트","기사 읽기","뉴스로 돌아가기","언어","지역","자동","게시","업데이트","이 지역에 게시된 뉴스가 아직 없습니다.","현재 관련된 활성 시장이 없습니다.","실시간 확률","DropsBot에서 추적","시장 보기","예","아니요","거래량","기계 번역 · 영어 원문","원문 보기","편집부 소개","세계의 사건. 명확한 맥락. 실시간 확률.","보관함","더 보기","확대","축소","닫기","확률 변화 · 7일","이 위치의 이전 시장","이 위치의 다음 시장","시장","중","지도를 불러오는 중…","대화형 지도를 사용할 수 없습니다","지도를 시작하지 못했습니다.","최근 확인된 이벤트를 목록에서 볼 수 있습니다.","지도 제어","이벤트 선택","시장 활동","알림 닫기","확률 업데이트 중…","뉴스 검색","검색 결과가 없습니다.","RSS 피드","국가","지도 탐색","출처 날짜","국가별 뉴스","언어 및 지역","원본 보도 링크를 포함한 독립적인 맥락 분석.","출처 읽기","분 읽기"],
  vi: ["Tin tức","Bản đồ","Tất cả quốc gia","Tin mới nhất","Nguồn","Sự kiện liên quan","Đọc bài","Về trang tin","Ngôn ngữ","Khu vực","Tự động","Đã đăng","Đã cập nhật","Chưa có tin được đăng cho khu vực này.","Hiện chưa có thị trường liên quan đang hoạt động.","Xác suất trực tiếp","Theo dõi trên DropsBot","Xem thị trường","CÓ","KHÔNG","Khối lượng","Bản dịch máy · Bản gốc tiếng Anh","Xem bản gốc","Về ban biên tập","Sự kiện thế giới. Bối cảnh rõ ràng. Xác suất trực tiếp.","Lưu trữ","Tải thêm","Phóng to","Thu nhỏ","Đóng","Thay đổi xác suất · 7 ngày","Thị trường trước tại vị trí này","Thị trường tiếp theo tại vị trí này","Thị trường","trên","Đang tải bản đồ…","Bản đồ tương tác không khả dụng","Không thể khởi động bản đồ.","Các sự kiện được xác minh gần nhất vẫn có trong danh sách.","Điều khiển bản đồ","Chọn sự kiện","Hoạt động thị trường","Ẩn thông báo","Đang cập nhật xác suất…","Tìm tin tức","Không tìm thấy bài phù hợp.","Nguồn RSS","Quốc gia","Khám phá bản đồ","Ngày của nguồn","Tin theo quốc gia","Ngôn ngữ và khu vực","Bối cảnh độc lập kèm liên kết đến bài gốc.","Đọc nguồn","phút đọc"],
  fa: ["اخبار","نقشه","همه کشورها","تازه‌ترین اخبار","منابع","رویدادهای مرتبط","خواندن خبر","بازگشت به اخبار","زبان","منطقه","خودکار","منتشر شده","به‌روزرسانی","هنوز خبری برای این منطقه منتشر نشده است.","در حال حاضر بازار فعال مرتبطی وجود ندارد.","احتمال‌های زنده","پیگیری در DropsBot","مشاهده بازار","بله","خیر","حجم","ترجمه ماشینی · متن اصلی انگلیسی","مشاهده متن اصلی","درباره تحریریه","رویدادهای جهان. زمینه روشن. احتمال‌های زنده.","آرشیو","نمایش بیشتر","بزرگ‌نمایی","کوچک‌نمایی","بستن","تغییر احتمال · ۷ روز","بازار قبلی در این مکان","بازار بعدی در این مکان","بازار","از","در حال بارگذاری نقشه…","نقشه تعاملی در دسترس نیست","نقشه راه‌اندازی نشد.","آخرین رویدادهای تأییدشده در فهرست موجود است.","کنترل نقشه","انتخاب رویداد","فعالیت بازار","بستن اعلان","در حال به‌روزرسانی احتمال‌ها…","جستجوی اخبار","خبری مطابق جستجو یافت نشد.","خوراک RSS","کشور","کاوش نقشه","تاریخ منبع","اخبار کشور","زبان و منطقه","زمینه مستقل با پیوند به گزارش‌های اصلی.","خواندن منبع","دقیقه مطالعه"],
  he: ["חדשות","מפה","כל המדינות","חדשות אחרונות","מקורות","אירועים קשורים","קריאת הכתבה","חזרה לחדשות","שפה","אזור","אוטומטי","פורסם","עודכן","עדיין אין כתבות שפורסמו באזור זה.","אין כרגע שווקים פעילים קשורים.","הסתברויות בזמן אמת","מעקב ב-DropsBot","הצגת השוק","כן","לא","נפח","תרגום מכונה · מקור באנגלית","הצגת המקור","על המערכת","אירועים בעולם. הקשר ברור. הסתברויות בזמן אמת.","ארכיון","טעינת עוד","הגדלה","הקטנה","סגירה","שינוי בהסתברות · 7 ימים","השוק הקודם במיקום זה","השוק הבא במיקום זה","שוק","מתוך","טוען את המפה…","המפה האינטראקטיבית אינה זמינה","לא ניתן להפעיל את המפה.","האירועים המאומתים האחרונים זמינים ברשימה.","פקדי מפה","בחירת אירוע","פעילות בשווקים","סגירת התראה","מעדכן הסתברויות…","חיפוש חדשות","לא נמצאו כתבות תואמות.","ערוץ RSS","מדינה","לגלות את המפה","תאריך המקור","חדשות לפי מדינה","שפה ואזור","הקשר עצמאי עם קישורים לדיווחים המקוריים.","קריאת המקור","דקות קריאה"],
};
export function message(locale: Locale, key: MessageKey): string {
  if (locale === "en") return ENGLISH_MESSAGES[key];
  return translations[locale][ORDER.indexOf(key)] ?? ENGLISH_MESSAGES[key];
}
export function validateMessageCoverage() {
  return Object.values(translations).every(values => values.length === ORDER.length && values.every(Boolean));
}
