import type { Metadata } from "next";
import { notFound, permanentRedirect } from "next/navigation";
import { NewsArticleView } from "@/components/news/news";
import { getNewsArticle } from "@/lib/news/catalog";
import { normalizeLocale, articleText } from "@/lib/news/locale";
import { LOCALES } from "@/lib/news/types";
import { getConflictPreviewFeed } from "@/lib/polymarket-conflict-preview";
type Props={params:Promise<{country:string;slug:string}>;searchParams:Promise<{lang?:string}>};
export const revalidate=60;
export async function generateMetadata({params,searchParams}:Props):Promise<Metadata>{const {country,slug}=await params;const article=await getNewsArticle(slug);if(!article)return {title:"Article not found | OddsFront"};const locale=normalizeLocale((await searchParams).lang)??"en";const text=articleText(article,locale);const url=`/news/${country}/${slug}`;return {title:`${text.title} | OddsFront`,description:text.description,alternates:{canonical:locale==="en"?url:`${url}?lang=${locale}`,languages:Object.fromEntries(LOCALES.map(language=>[language,language==="en"?url:`${url}?lang=${language}`]))},openGraph:{type:"article",title:text.title,description:text.description,publishedTime:article.publishedAt,modifiedTime:article.updatedAt,url}};}
export default async function ArticlePage({params}:Props){const {country,slug}=await params;const [article,feed]=await Promise.all([getNewsArticle(slug),getConflictPreviewFeed()]);if(!article)notFound();const canonicalCountry=(article.countries[0]||"world").toLowerCase();if(country!==canonicalCountry)permanentRedirect(`/news/${canonicalCountry}/${article.slug}`);const structured={"@context":"https://schema.org","@type":"NewsArticle",headline:article.title,description:article.description,datePublished:article.publishedAt,dateModified:article.updatedAt,author:{"@type":"Organization",name:article.author},publisher:{"@type":"Organization",name:"OddsFront"},mainEntityOfPage:`https://oddsfront.com/news/${country}/${slug}`,citation:article.sources.map(source=>source.url)};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,"\\u003c")}}/><NewsArticleView article={article} initialFeed={feed}/></>;}
